# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'deploygate-ios-sdk-swift-sample' do
  pod 'DeployGateSDK'
end

target 'deploygate-ios-sdk-swift-sampleTests' do

end

